package com.udacity.pricing.domain.price;

import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;

/**
 * PriceRepository
 * This repository provide a type of data persistence while the web service runs,
 * namely the ID->price pairing generated by the PricingService.
 */
@Repository
public interface PriceRepository extends CrudRepository<Price, Long> {


}
